@startuml
participant "Client\nLibrary" as lib
participant "Crinit" as srv

lib -> srv : ""connect()""
srv -> lib : ""accept()""
srv -> srv : set ""SO_PASSCRED""
srv -> lib : send ""RTR""
group Using ""sendStr()""/""recvStr()""\nor ""crinitSend()""/""crinitRecv()""
lib -> srv : send request
srv -> lib : send answer
end

@enduml
